networks:
  monitor-net:
    driver: bridge
  caddy-net:
    external: true

volumes:
    prometheus_data: {}
    grafana_data: {}
    prometheus_config: {}
    alertmanager_config: {}
    grafana_config: {}
    alertmanager_data: {}
    uptime-kuma_data:
      external: true
    promtail_config: {}
    loki_config: {}

services:

  # Workaround to the lack of relative paths volumes in Portainer stacks
  # see https://github.com/portainer/portainer/issues/6390#issuecomment-1100954657
  git-checkout:
    image: bitnami/git:latest
    working_dir: /temp
    command: >
      bash -c " 
        git clone https://github.com/axeleroy/dockprom.git &&
        echo 'Copying ./dockprom/prometheus ...' &&
        sed -i \"s/<UPTIME_KUMA_USERNAME>/$UPTIME_KUMA_USERNAME/g\" ./dockprom/prometheus/prometheus.yml &&
        sed -i \"s/<UPTIME_KUMA_PASSWORD>/$UPTIME_KUMA_PASSWORD/g\" ./dockprom/prometheus/prometheus.yml &&
        cp -R ./dockprom/prometheus/. /prometheus_config &&
        echo 'Copying ./dockprom/alertmanager ...' &&
        sed -i \"s/<PUSHOVER_USER_KEY>/$PUSHOVER_USER_KEY/g\" ./dockprom/alertmanager/config.yml &&
        sed -i \"s/<PUSHOVER_TOKEN>/$PUSHOVER_TOKEN/g\" ./dockprom/alertmanager/config.yml &&
        cp -R ./dockprom/alertmanager/. /alertmanager_config &&
        echo 'Copying ./dockprom/grafana/provisioning ...' &&
        cp -R ./dockprom/grafana/provisioning/. /grafana_config &&
        echo 'Copying ./dockprom/promtail ...' &&
        cp -R ./dockprom/promtail/. /promtail_config &&
        echo 'Copying ./dockprom/loki ...' &&
        cp -R ./dockprom/loki/. /loki_config &&
        echo 'Copying done!'
      "
    volumes:
      - prometheus_config:/prometheus_config
      - alertmanager_config:/alertmanager_config
      - grafana_config:/grafana_config
      - loki_config:/loki_config
      - promtail_config:/promtail_config
    environment:
      - UPTIME_KUMA_USERNAME
      - UPTIME_KUMA_PASSWORD
      - PUSHOVER_USER_KEY
      - PUSHOVER_TOKEN

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    depends_on:
      - git-checkout
    volumes:
      - prometheus_config:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net
      - caddy-net
    labels:
      org.label-schema.group: "monitoring"
      caddy: prometheus.local.axeleroy.com
      caddy.reverse_proxy: "{{upstreams 9090}}"
      caddy.import: ovh
      homepage.group: Monitoring
      homepage.name: Prometheus
      homepage.icon: prometheus
      homepage.href: https://prometheus.local.axeleroy.com
      homepage.widget.type: prometheus
      homepage.widget.url: http://prometheus:9090

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    depends_on:
      - git-checkout
    volumes:
      - alertmanager_config:/etc/alertmanager
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - monitor-net
      - caddy-net
    labels:
      org.label-schema.group: "monitoring"
      caddy: alertmanager.local.axeleroy.com
      caddy.reverse_proxy: "{{upstreams 9093}}"
      caddy.import: ovh
      homepage.group: Monitoring
      homepage.name: Alert Manager
      homepage.icon: alertmanager
      homepage.href: https://alertmanager.local.axeleroy.com

  nodeexporter:
    image: prom/node-exporter:v1.8.0
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    depends_on:
      - git-checkout
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      #- GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
      - caddy-net
    labels:
      org.label-schema.group: "monitoring"
      caddy: grafana.local.axeleroy.com
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.import: ovh
      homepage.group: Monitoring
      homepage.name: Grafana
      homepage.icon: grafana
      homepage.href: https://grafana.local.axeleroy.com
      homepage.widget.type: grafana
      homepage.widget.url: http://grafana:3000
      homepage.widget.user: ${ADMIN_USER:-admin}
      homepage.widget.password: ${ADMIN_PASSWORD:-admin}

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    expose:
      - 3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitor-net
    restart: unless-stopped
    depends_on:
      - git-checkout
    volumes:
      - loki_config:/etc/loki
    labels:
      org.label-schema.group: "monitoring"
  
  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - promtail_config:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    depends_on:
      - git-checkout
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  pushgateway:
    image: prom/pushgateway:v1.8.0
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nut-exporter:
    image: hon95/prometheus-nut-exporter:1.2.1
    container_name: nut-exporter
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - HTTP_PATH=/metrics
    expose:
      - 9995
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nginxexporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: nginx-exporter
    restart: unless-stopped
    command:
      - -nginx.scrape-uri=http://${NGINX_HOST:-localhost}:8080/stub_status/
    expose:
      - 9113
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  pihole-exporter:
    image: ekofr/pihole-exporter:v0.4.0
    container_name: pihole-exporter
    restart: unless-stopped
    environment:
      - PIHOLE_HOSTNAME=pihole
      - PIHOLE_PASSWORD=${PIHOLE_PASSWORD:-pihole}
      - PORT=9617
    networks:
      - monitor-net
    expose:
      - 9617
    labels:
      org.label-schema.group: "monitoring"

  uptime-kuma:
    image: louislam/uptime-kuma:${UPTIME_KUMA_VERSION:-1.23.11}
    container_name: uptime-kuma
    expose:
      - 3001
    volumes:
      - uptime-kuma_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - caddy-net
      - monitor-net
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 9.9.9.9
    labels:  
      org.label-schema.group: "monitoring"
      caddy: uptime.local.axeleroy.com
      caddy.reverse_proxy: "{{upstreams 3001}}"
      caddy.import: ovh
      homepage.group: Monitoring
      homepage.name: Uptime Kuma
      homepage.icon: uptime-kuma
      homepage.href: https://uptime.local.axeleroy.com
      homepage.widget.type: uptimekuma
      homepage.widget.url: http://uptime-kuma:3001
      homepage.widget.slug: default
      

