server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
#        filters:
#          - name: name
#            values: [ flog ]
    relabel_configs:
      - source_labels: [ '__meta_docker_container_name' ]
        regex: '/(.*)'
        target_label: 'container'

#  - job_name: containers
#
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: containerlogs
#          __path__: /var/lib/docker/containers/*/*log
#
#    # --log-opt tag="{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
#    # Enable JSON logs https://gist.github.com/ruanbekker/c6fa9bc6882e6f324b4319c5e3622460?permalink_comment_id=3720738#gistcomment-3720738
#    pipeline_stages:
#      - json:
#          expressions:
#            output: log
#            stream: stream
#            attrs:
#      - json:
#          expressions:
#            tag:
#          source: attrs
#      - regex:
#          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
#          source: tag
#      - timestamp:
#          format: RFC3339Nano
#          source: time
#      - labels:
#          tag:
#          stream:
#          image_name:
#          container_name:
#          image_id:
#          container_id:
#      - output:
#          source: output

